repos:
  - repo: https://github.com/psf/black
    rev: 26.3.0
    hooks:
      - id: black
        args: ["--line-length=120"]
        files: "^(utils|scripts|tests)/.*\\.py$"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff
        args: ["--fix"]
        files: "^(utils|scripts|tests)/.*\\.py$"
