#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Upload generated vertical videos to YouTube Shorts."""
from __future__ import annotations

import json
import logging
import os
import random
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload

_LANGUAGE = os.environ.get("LANGUAGE", "en").strip() or "en"
LOG_FILE = f"upload_youtube{'' if _LANGUAGE == 'en' else '_' + _LANGUAGE}.log"
VIDEOS_DIR = Path("_videos") if _LANGUAGE == "en" else Path(f"_videos_{_LANGUAGE}")
TOKEN_FILE = Path("youtube_token.json")
SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.readonly",
    "https://www.googleapis.com/auth/youtube.force-ssl",
    "https://www.googleapis.com/auth/yt-analytics.readonly",
]
RETRIABLE_STATUS_CODES = {500, 502, 503, 504}
MAX_RETRIES = 6

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s", handlers=[logging.FileHandler(LOG_FILE, encoding="utf-8"), logging.StreamHandler()])
log = logging.getLogger(__name__)


def _load_credentials() -> Credentials:
    if not TOKEN_FILE.exists():
        raise FileNotFoundError("youtube_token.json not found. Set the YOUTUBE_TOKEN GitHub secret with the JSON generated by auth_youtube.py.")
    data = json.loads(TOKEN_FILE.read_text(encoding="utf-8").strip())
    creds = Credentials.from_authorized_user_info(data, SCOPES)
    if not creds.valid:
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            TOKEN_FILE.write_text(creds.to_json(), encoding="utf-8")
        else:
            raise RuntimeError("YouTube credentials are invalid. Run auth_youtube.py again and update YOUTUBE_TOKEN.")
    return creds


def get_youtube_service():
    return build("youtube", "v3", credentials=_load_credentials(), cache_discovery=False)


def _collect_pending_meta(videos_dir: Path) -> list[Path]:
    return sorted(p for p in videos_dir.glob("*.json") if p.stem.startswith(("short-", "roundup-")))


def _normalise_tags(tags) -> list[str]:
    out, seen = [], set()
    for tag in tags or []:
        t = str(tag).strip().lstrip("#")
        if t and t.lower() not in seen:
            out.append(t[:30]); seen.add(t.lower())
        if len(out) >= 15:
            break
    return out


def _youtube_title(meta: dict) -> str:
    title = (meta.get("title") or "Animal fact of the day").strip()
    return title if len(title) <= 100 else title[:97].rstrip(" .,;:-") + "..."


def _youtube_description(meta: dict) -> str:
    description = (meta.get("description") or _youtube_title(meta)).strip()
    existing = {part.lower() for part in description.split() if part.startswith("#")}
    missing = [tag for tag in ("#Shorts", "#AnimalFacts", "#Wildlife") if tag.lower() not in existing]
    if missing:
        description += "\n\n" + " ".join(missing)
    source = (meta.get("source_url") or "").strip()
    if source and source not in description:
        description += "\n\nSource: " + source
    return description[:5000]


def _video_url(video_id: str) -> str:
    return f"https://www.youtube.com/shorts/{video_id}" if video_id else ""


def _is_uploadable_meta(meta: dict) -> bool:
    audit = meta.get("pre_publish_audit")
    if isinstance(audit, dict) and audit.get("approved") is False:
        return False
    return Path(meta.get("video") or "").is_file()


def _done_marker(video_id: str, meta: dict) -> dict:
    """Persist the production signals needed by analytics and digest."""
    keys = (
        "title", "description", "tags", "category", "series", "editorial",
        "is_short", "has_broll", "has_captions", "script_quality_grade",
        "production_quality", "pexels_video_id", "pexels_download_url",
        "source_clip_id", "source", "source_url", "source_license",
        "commons_page_url", "commons_license", "commons_artist", "gbif",
        "visual_qa", "visual_ctr", "experiments",
        "hook", "story_format", "hook_audit", "title_audit", "narrator_voice",
        "human_voice", "humanity", "studio_polish", "studio_state", "ai_rewrite",
        "pre_publish_audit", "monetization_audit", "seo_score", "seo_optimisation",
        "publish_score", "youtube_brain", "packaging", "pinned_comment",
    )
    defaults = {
        "title": "", "description": "", "tags": [], "category": "",
        "series": "", "editorial": {}, "is_short": True, "has_broll": False,
        "has_captions": False, "production_quality": {}, "pexels_video_id": "",
        "pexels_download_url": "", "source_clip_id": "", "source": "",
        "source_url": "", "source_license": "", "commons_page_url": "",
        "commons_license": "", "commons_artist": "", "gbif": {},
        "visual_qa": {}, "visual_ctr": {}, "experiments": {},
        "hook": "", "story_format": "", "hook_audit": {}, "title_audit": {},
        "narrator_voice": "",
        "human_voice": {}, "humanity": {}, "studio_polish": {}, "studio_state": "",
        "ai_rewrite": {}, "pre_publish_audit": {}, "monetization_audit": {},
        "seo_score": {}, "seo_optimisation": {},
        "publish_score": {}, "youtube_brain": {}, "packaging": {}, "pinned_comment": "",
    }
    marker = {key: meta.get(key, defaults.get(key)) for key in keys}
    marker.update({
        "video_id": video_id,
        "url": _video_url(video_id),
        "uploaded_at": datetime.now(timezone.utc).isoformat(),
        "platform": "youtube",
        "language": _LANGUAGE,
    })
    return marker


def _execute_resumable(request) -> dict:
    response, retry = None, 0
    while response is None:
        try:
            status, response = request.next_chunk()
            if status:
                log.info("Upload: %d%%", int(status.progress() * 100))
        except HttpError as exc:
            if exc.resp.status not in RETRIABLE_STATUS_CODES:
                raise
            error = f"HTTP {exc.resp.status}"
        except (OSError, TimeoutError) as exc:
            error = f"{type(exc).__name__}: {exc}"
        else:
            continue
        retry += 1
        if retry > MAX_RETRIES:
            raise RuntimeError(f"YouTube upload failed after retries: {error}")
        time.sleep(random.uniform(1, 2 ** retry))
    return response


def upload_video(youtube, meta: dict) -> str | None:
    video_path = Path(meta.get("video") or "")
    if not video_path.exists():
        log.error("Video not found: %s", video_path)
        return None
    privacy = (os.environ.get("YOUTUBE_PRIVACY") or meta.get("youtube_privacy") or "public").strip().lower()
    if privacy not in {"public", "unlisted", "private"}:
        privacy = "public"
    request = youtube.videos().insert(part="snippet,status", body={"snippet": {"title": _youtube_title(meta), "description": _youtube_description(meta), "tags": _normalise_tags(meta.get("tags")), "categoryId": str(meta.get("youtube_category_id") or "15")}, "status": {"privacyStatus": privacy, "selfDeclaredMadeForKids": False}}, media_body=MediaFileUpload(str(video_path), mimetype="video/mp4", chunksize=-1, resumable=True), notifySubscribers=False)
    response = _execute_resumable(request)
    video_id = response.get("id")
    if not video_id:
        return None
    thumb = Path(meta.get("thumbnail") or "")
    if thumb.exists():
        try:
            youtube.thumbnails().set(videoId=video_id, media_body=MediaFileUpload(str(thumb))).execute()
        except HttpError as exc:
            log.warning("Thumbnail upload failed: HTTP %s", exc.resp.status)
    log.info("Published: %s", _video_url(video_id))
    return video_id


def main() -> None:
    from utils.panic import abort_if_halted
    abort_if_halted("upload_youtube")
    try:
        youtube = get_youtube_service()
    except Exception as exc:
        log.error("YouTube auth failed: %s", exc); sys.exit(2)
    pending, attempted, uploaded = _collect_pending_meta(VIDEOS_DIR), 0, 0
    for meta_file in pending:
        try:
            meta = json.loads(meta_file.read_text(encoding="utf-8"))
        except Exception as exc:
            log.error("Failed to read %s: %s", meta_file.name, exc); continue
        if not isinstance(meta, dict):
            continue
        if not _is_uploadable_meta(meta):
            log.warning("Skipping orphan metadata without video: %s", meta_file.name)
            continue
        attempted += 1
        video_id = upload_video(youtube, meta)
        if not video_id:
            continue
        meta_file.with_suffix(".done").write_text(
            json.dumps(_done_marker(video_id, meta), indent=2),
            encoding="utf-8",
        )
        try:
            from fetch_animals import record_published_clip
            record_published_clip(pexels_video_id=meta.get("pexels_video_id", ""), story_id=meta.get("story_id", ""), pexels_url=meta.get("pexels_download_url", ""), source_clip_id=meta.get("source_clip_id", ""), source=meta.get("source", ""), source_url=meta.get("source_url", ""), platform_video_id=video_id)
        except Exception as exc:
            log.warning("published_clips ledger update failed: %s", exc)
        meta_file.unlink(); uploaded += 1
    log.info("%d/%d video(s) uploaded to YouTube.", uploaded, attempted)
    if attempted and uploaded == 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
