#!/usr/bin/env python3
"""One-time (re-runnable) pass: brand the thumbnail and refresh tags for
every video published before the generators started branding thumbnails
themselves, using the same utils/thumbnail_branding.py template and niche
tag vocabulary new uploads already get automatically. Approved in chat on
2026-07-19 as a follow-up once titles were confirmed consistent.

For each video: recover its display hook straight from the (already
correct, freshly rebranded) title, fetch its current public thumbnail,
run it through the same branding function the generators use for new
uploads, and push both the branded thumbnail (thumbnails().set) and
refreshed tags (videos().update) back to YouTube. Title/description/
category are resent unmodified for the same reason rebrand_video_titles.py
does: videos.update needs the full snippet or it wipes whatever isn't
included.

A Short's *generated* thumbnail file from YouTube is always a 1280x720
(16:9) container with the real 9:16 video pillarboxed in the center --
checked live, branding that whole container draws the moon/skyline/text
over the blurred padding instead of the actual scene, so the vertical
strip is cropped out first (_extract_vertical_content).
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path

import requests
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from generate_lofi_mix import DEFAULT_TAGS as MIX_DEFAULT_TAGS  # noqa: E402
from generate_lofi_short import DEFAULT_TAGS as SHORT_DEFAULT_TAGS  # noqa: E402
from upload_youtube import _normalise_tags, get_youtube_service  # noqa: E402
from utils.thumbnail_branding import brand_mix_thumbnail, brand_short_thumbnail  # noqa: E402

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("rebrand_video_thumbnails")

VIDEOS_DIR = Path("_videos")
THUMB_TIMEOUT_S = 20
# Epoch seconds when 426a5fb7f ("Give Shorts and the horizontal mix a
# branded thumbnail") went live -- any marker slug timestamped after this
# was generated by a pipeline that already branded its own thumbnail, so
# re-processing it here would brand an already-branded image a second
# time (checked live: produces a smaller nested copy of the template
# inside the panel/frame).
_THUMBNAIL_BRANDING_DEPLOYED_AT = 1784419627
# thumbnails().set() has its own per-account rate limit, separate from the
# daily quota budget. Checked live, twice: blasting through calls with no
# delay hits "uploadRateLimitExceeded" (HTTP 429) on call #2; spacing
# calls 8s apart and backing off up to 30+60+120s on a 429 *still* didn't
# clear it for several videos in a row -- this isn't a short burst window,
# it's a longer-lived cooldown no in-job retry can wait out without
# blowing the workflow timeout. A small courtesy delay is kept, but a 429
# now stops the whole run instead of retrying: whatever got applied
# stays applied (idempotent marker check means the rest just picks up on
# the next run), and the job exits quickly instead of burning ~20 minutes
# retrying calls that won't succeed.
_BETWEEN_VIDEOS_S = 3.0


class _RateLimited(Exception):
    pass


def _set_thumbnail(youtube, video_id: str, thumb_path: Path) -> None:
    try:
        youtube.thumbnails().set(videoId=video_id, media_body=MediaFileUpload(str(thumb_path))).execute()
    except HttpError as exc:
        if exc.resp.status == 429:
            raise _RateLimited(str(exc)) from exc
        raise


# Checked in order; YouTube serves a small grey placeholder JPEG (~1-2 KB)
# for a resolution it never generated for a given video, so falling
# through on a tiny response is how a real still gets found.
_THUMB_SIZES = ("maxresdefault.jpg", "sddefault.jpg", "hqdefault.jpg", "mqdefault.jpg")
_PLACEHOLDER_MAX_BYTES = 2000


def _slug_timestamp(marker_path: Path) -> int:
    """Every marker is named "{short,mix}-...-{epoch}-{rand}.done" (see
    generate_lofi_short.py/generate_lofi_mix.py's slug = f"...{int(time.time())}-...").
    """
    parts = marker_path.stem.split("-")
    for part in reversed(parts):
        if part.isdigit() and len(part) >= 9:
            return int(part)
    return 0


def _read_json(path: Path) -> dict:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def _hook_from_title(title: str) -> str:
    """Extract the display hook straight from an already-branded title,
    e.g. "Rainy Night Anime Lofi — Amber Hours 🌧️" -> "Rainy Night".

    Deliberately not derived from the marker's description: mix
    descriptions have a "1 hour of ..." prefix and the oldest markers'
    descriptions predate today's mood-labelling fixes, so parsing them
    back out is fragile. The title is already correct for every video on
    the channel as of today's rebrand, so it's the reliable source.
    """
    text = (title or "").strip()
    dash_idx = text.find("—")
    if dash_idx > 0:
        text = text[:dash_idx].strip()
    text = text.replace("(1 Hour)", "").strip()
    if text.endswith(" Anime Lofi"):
        text = text[: -len(" Anime Lofi")].strip()
    return text or "Cozy"


def _download_thumbnail(video_id: str, dest: Path) -> bool:
    for name in _THUMB_SIZES:
        url = f"https://i.ytimg.com/vi/{video_id}/{name}"
        try:
            response = requests.get(url, timeout=THUMB_TIMEOUT_S)
        except Exception as exc:
            log.warning("thumbnail fetch failed for %s (%s): %s", video_id, name, exc)
            continue
        if response.status_code != 200 or len(response.content) < _PLACEHOLDER_MAX_BYTES:
            continue
        dest.write_bytes(response.content)
        return True
    return False


def _extract_vertical_content(path: Path) -> None:
    """A Short's generated thumbnail file is always a 1280x720 (16:9)
    container with the real 9:16 video pillarboxed in the center (checked
    live: downloading one and inspecting it showed exactly this) --
    branding that whole container as if it were full-bleed vertical
    content draws the moon/skyline/text over the blurred padding instead
    of the actual scene. Crop out just the true vertical strip first."""
    im = Image.open(path)
    w, h = im.size
    if w <= h:
        return
    target_w = int(h * 9 / 16)
    x0 = (w - target_w) // 2
    im.crop((x0, 0, x0 + target_w, h)).convert("RGB").save(path, quality=95)


def build_plan(videos_dir: Path = VIDEOS_DIR) -> list[dict]:
    plans: list[dict] = []
    for path in sorted(videos_dir.glob("*.done")):
        marker = _read_json(path)
        video_id = str(marker.get("video_id") or "")
        if not video_id:
            continue
        is_mix = path.name.startswith("mix-")
        mood = _hook_from_title(str(marker.get("title") or ""))
        base_tags = MIX_DEFAULT_TAGS if is_mix else SHORT_DEFAULT_TAGS
        tags = _normalise_tags(list(base_tags) + [mood.lower()])
        generated_after_deploy = _slug_timestamp(path) >= _THUMBNAIL_BRANDING_DEPLOYED_AT
        plans.append(
            {
                "marker": str(path),
                "video_id": video_id,
                "is_mix": is_mix,
                "mood": mood,
                "title": str(marker.get("title") or ""),
                "description": str(marker.get("description") or ""),
                "category_id": "10" if is_mix else "15",
                "tags": tags,
                "already_done": bool(marker.get("thumbnail_retag")) or generated_after_deploy,
            }
        )
    return plans


def apply_plan(youtube, plan: dict, tmp_dir: Path) -> None:
    thumb_path = tmp_dir / f"{plan['video_id']}.jpg"
    if not _download_thumbnail(plan["video_id"], thumb_path):
        raise RuntimeError("could not fetch a real thumbnail (every size came back a placeholder)")
    if plan["is_mix"]:
        brand_mix_thumbnail(thumb_path, plan["mood"])
    else:
        _extract_vertical_content(thumb_path)
        brand_short_thumbnail(thumb_path, plan["mood"])
    _set_thumbnail(youtube, plan["video_id"], thumb_path)
    snippet = {
        "title": plan["title"],
        "description": plan["description"],
        "tags": plan["tags"],
        "categoryId": plan["category_id"],
    }
    youtube.videos().update(part="snippet", body={"id": plan["video_id"], "snippet": snippet}).execute()


def write_marker_done(plan: dict) -> None:
    path = Path(plan["marker"])
    marker = _read_json(path)
    if not marker:
        return
    marker["tags"] = plan["tags"]
    marker["thumbnail_retag"] = {
        "mood": plan["mood"],
        "tags": plan["tags"],
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "reason": "niche_thumbnail_and_tags_2026-07-19",
    }
    path.write_text(json.dumps(marker, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--videos-dir", default=str(VIDEOS_DIR))
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    videos_dir = Path(args.videos_dir)
    plans = build_plan(videos_dir)
    runnable = [p for p in plans if not p["already_done"]]
    applied: list[dict] = []
    failed: list[dict] = []
    rate_limited = False

    if args.apply and runnable:
        youtube = get_youtube_service()
        with tempfile.TemporaryDirectory() as tmp:
            tmp_dir = Path(tmp)
            for i, plan in enumerate(runnable):
                if i:
                    time.sleep(_BETWEEN_VIDEOS_S)
                try:
                    apply_plan(youtube, plan, tmp_dir)
                except _RateLimited as exc:
                    log.warning(
                        "thumbnail upload rate-limited at %s -- stopping this run, %d/%d already applied: %s",
                        plan["video_id"],
                        len(applied),
                        len(runnable),
                        exc,
                    )
                    failed.append({"video_id": plan["video_id"], "error": f"rate_limited: {exc}"})
                    rate_limited = True
                    break
                except Exception as exc:
                    log.warning("thumbnail/tag refresh failed for %s: %s", plan["video_id"], exc)
                    failed.append({"video_id": plan["video_id"], "error": str(exc)})
                    continue
                write_marker_done(plan)
                applied.append({"video_id": plan["video_id"], "mood": plan["mood"]})

    payload = {
        "planned": len(runnable),
        "applied": len(applied),
        "failed": failed,
        "rate_limited": rate_limited,
        "plans": plans,
    }
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        for plan in plans:
            status = "done" if plan["already_done"] else "pending"
            print(f"{plan['video_id']} [{status}] mood={plan['mood']!r}")
        print(f"planned={len(runnable)} applied={len(applied)} failed={len(failed)}")
    return 1 if failed and not applied else 0


if __name__ == "__main__":
    sys.exit(main())
