name: "Pata Jazz YouTube Live"
on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Motivo"
        required: false
        default: "manual"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.reason }}"
